# Generated by Django 4.2.5 on 2023-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favourite_genre',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0', max_length=15),
            preserve_default=False,
        ),
    ]
